before_script:
  - apt-get update -qq && apt-get install -y -qq libhdf5-dev
  - pip install -U pip setuptools wheel
  - pip install .

test:
    image: python:3.7.0
    script:
        - echo narf

pages:
    image: python:3.7.0
    script:
        - cd docs && make html
        - mv _build/html/ ../public/
    artifacts:
        paths:
            - public
