stages:
  - test
  - doc
  - release

before_script:
  - apt-get update -qq && apt-get install -y -qq libhdf5-dev
  - pip install -U pip setuptools wheel numpy
  - pip install .

test:
    image: docker.km3net.de/base/python:3
    stage: test
    script:
        - echo narf

pages:
    image: docker.km3net.de/base/python:3
    stage: doc
    script:
        - cd docs && make html
        - mv _build/html/ ../public/
    artifacts:
        paths:
            - public

pypi:
    image: docker.km3net.de/base/python:3
    stage: release
    cache: {}
    script:
        - pip install -U twine
        - python setup.py sdist
        - twine upload dist/*
    only:
        - tags

